[package]
name = "storage_buffers"
version.workspace = true
authors.workspace = true
edition.workspace = true


[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "GpuDevice",
    "GpuCanvasContext",
    "GpuTextureFormat",
    "GpuShaderModuleDescriptor",
    "GpuShaderModule",
    "GpuVertexState",
    "GpuColorTargetState",
    "GpuFragmentState",
    "GpuRenderPipelineDescriptor",
    "GpuRenderPipeline",
    "GpuRenderPassColorAttachment",
    "GpuLoadOp",
    "GpuStoreOp",
    "GpuColorDict",
    "GpuRenderPassDescriptor",
    "GpuTexture",
    "GpuTextureView",
    "GpuCommandEncoder",
    "GpuRenderPassDescriptor",
    "GpuRenderPassEncoder",
    "GpuCommandBuffer",
    "GpuQueue",
    "GpuComputePipelineDescriptor",
    "GpuComputePipeline",
    "GpuProgrammableStage",
    "GpuBufferDescriptor",
    "GpuBuffer",
    "GpuBindGroupDescriptor",
    "GpuBindGroup",
    "GpuBindGroupLayout",
    "GpuBindGroupEntry",
    "GpuBufferBinding",
    "GpuComputePassDescriptor",
    "GpuComputePassEncoder",
    "gpu_buffer_usage",
    "gpu_map_mode",
    "GpuBindGroupLayoutEntry",
    "GpuBufferBindingLayout",
    "GpuBufferBindingType",
    "GpuBindGroupLayoutDescriptor",
    "gpu_shader_stage",
    "HtmlCanvasElement",
] }

js-sys.workspace = true

rand = "0.9.2"
getrandom = { version = "0.3.4", features = ["wasm_js"] }
